<?php
// phpcs:disable Generic.Files.LineLength

return [

    // Panel page title
    'title_home' => 'Visão Geral',
    'title_overview' => 'Visão Geral',
    'title_iptables_manager' => 'Gerenciador de IpTables',
    'title_iptables_status' => 'Status do IpTables',
    'title_operation_status' => 'Status da Operação',
    'title_action_logs' => 'Logs de Ações',
    'title_web_authentication' => 'Autenticação da Página Web',
    'title_xss_protection' => 'Proteção XSS',
    'title_basic_setting' => 'Configurações Básicas',
    'title_messenger' => 'Notificações',
    'title_ip_manager' => 'Gerenciador de IPs',
    'title_exclusion_list' => 'Lista de Exclusão',
    'title_login' => 'Login no Painel do Firewall Shieldon',
    'title_title_site_wide' => 'Firewall Shieldon',
    'title_circle_rule' => 'Tabela de Regras',
    'title_circle_filter' => 'Tabela de Filtros',
    'title_circle_session' => 'Tabela de Sessões',
    
    // Motivos
    'reason_manual_ban' => 'Adicionado manualmente pelo administrador.',
    'reason_is_search_engine' => 'Bot de mecanismo de busca.',
    'reason_is_google' => 'Bot do Google.',
    'reason_is_bing' => 'Bot do Bing.',
    'reason_is_yahoo' => 'Bot do Yahoo.',
    'reason_too_many_sessions' => 'Sessões em excesso.',
    'reason_too_many_accesses' => 'Acessos em excesso.',
    'reason_empty_js_cookie' => 'Não foi possível criar cookies via JS.',
    'reason_empty_referer' => 'Referenciador ausente.',
    'reason_reached_limit_day' => 'Limite diário atingido.',
    'reason_reached_limit_hour' => 'Limite por hora atingido.',
    'reason_reached_limit_minute' => 'Limite por minuto atingido.',
    'reason_reached_limit_second' => 'Limite por segundo atingido.',
    'reason_invalid_ip' => 'Endereço IP inválido.',
    'reason_deny_ip' => 'Bloqueado pelo componente de IP.',
    'reason_allow_ip' => 'Permitido pelo componente de IP.',
    'reason_component_ip' => 'Bloqueado pelo componente de IP.',
    'reason_component_rdns' => 'Bloqueado pelo componente RDNS.',
    'reason_component_header' => 'Bloqueado pelo componente de Cabeçalho.',
    'reason_component_useragent' => 'Bloqueado pelo componente User Agent.',
    'reason_component_trusted_robot' => 'Identificado como bot de mecanismo de busca falso.',

    // Menu
    'nav_locale' => 'Idioma',
    'menu_firewall' => 'Firewall',
    'menu_status' => 'Status',
    'menu_overview' => 'Visão Geral',
    'menu_settings' => 'Configurações',
    'menu_ip_manager' => 'Gerenciador de IPs',
    'menu_xss_protection' => 'Proteção XSS',
    'menu_authentication' => 'Autenticação',
    'menu_exclusion' => 'Exclusão',
    'menu_last_month' => 'Mês passado',
    'menu_this_month' => 'Este mês',
    'menu_last_7_days' => 'Últimos 7 dias',
    'menu_yesterday' => 'Ontem',
    'menu_today' => 'Hoje',
    'menu_ip_filter_logs' => 'Logs de Filtro de IP',
    'menu_ip_rules' => 'Regras de IP',
    'menu_sessions' => 'Sessões',
    'menu_action_logs' => 'Logs de Ações',
    'menu_data_circle' => 'Círculo de Dados',
    'menu_operation_status' => 'Status da Operação',
    'menu_iptables_manager' => 'Gerenciador',
    'menu_iptables_status' => 'Status',
    'menu_messenger' => 'Notificações',
    'menu_iptables_bridge' => 'Bridge do iptables',
    'menu_iptables_ipv4' => 'iptables IPv4',
    'menu_iptables_ipv6' => 'iptables IPv6',
    
    // Mensagens
    'error_mysql_connection' => 'Não foi possível conectar ao banco de dados MySQL. Verifique suas configurações.',
    'error_mysql_driver_not_supported' => 'Seu sistema não oferece suporte ao driver MySQL.',
    'error_sqlite_driver_not_supported' => 'Seu sistema não oferece suporte ao driver SQLite.',
    'error_sqlite_directory_not_writable' => 'O driver SQLite requer permissão de escrita no diretório de armazenamento.',
    'error_redis_driver_not_supported' => 'Seu sistema não oferece suporte ao driver Redis.',
    'error_file_directory_not_writable' => 'O driver de arquivos requer permissão de escrita no diretório de armazenamento.',
    'error_logger_directory_not_writable' => 'O registrador de ações requer permissão de escrita no diretório de armazenamento.',
    'error_invalid_json_file' => 'Arquivo JSON inválido.',
    'error_invalid_config_file' => 'Arquivo de configuração do Shieldon inválido.',
    'success_settings_saved' => 'Configurações salvas com sucesso.',
    'success_json_imported' => 'Arquivo JSON importado com sucesso.',
    
    // Outros
    'field_not_visible' => 'Este campo não pode ser visualizado no modo demonstração.',
    'permission_required' => 'Permissão necessária.',
    
    // Barra de status do cabeçalho
    'channel' => 'Canal',
    'mode' => 'Modo',
    'logout' => 'Sair',
    
    // Configuração - página de autenticação
    'auth_heading' => 'Autenticação',
    'auth_description' => 'O cabeçalho de resposta HTTP WWW-Authenticate define o método de autenticação que deve ser usado para acessar um recurso.',
    'auth_label_url_path' => 'Caminho da URL',
    'auth_label_username' => 'Nome de usuário',
    'auth_label_password' => 'Senha',
    'auth_btn_submit' => 'Enviar',
    'auth_label_encrypted' => 'criptografado',
    'auth_label_remove' => 'Remover',


    // Setting - exclusion page.
    'excl_heading' => 'Exclusão',
    'excl_description' => 'Por favor, insira as URLs (ou inícios de URL) que você deseja excluir da proteção do Shieldon.',
    
    // Gerenciador de IPs
    'ipma_heading' => 'Gerenciador de IPs',
    'ipma_description' => 'O Gerenciador de IPs não é como a Tabela de Regras (que depende do ciclo de dados), tudo que você fizer aqui é permanente.',
    'ipma_label_ip' => 'IP',
    'ipma_label_order' => 'Ordem',
    'ipma_label_rule' => 'Regra',
    'ipma_label_action' => 'Ação',
    'ipma_label_plz_select' => 'Por favor, selecione',
    'ipma_label_remove_ip' => 'Remover este IP',
    'ipma_label_allow_ip' => 'Permitir este IP',
    'ipma_label_deny_ip' => 'Bloquear este IP',
    
    // Logs
    'log_heading_captchas' => 'CAPTCHAs',
    'log_heading_pageviews' => 'Visualizações de Página',
    'log_note_captcha_last_month' => 'Estatísticas de CAPTCHA do mês passado.',
    'log_note_pageview_last_month' => 'Total de visualizações de página no mês passado.',
    'log_note_captcha_last_7_days' => 'Estatísticas de CAPTCHA dos últimos 7 dias.',
    'log_note_pageview_last_7_days' => 'Total de visualizações de página nos últimos 7 dias.',
    'log_note_pageview_this_month' => 'Total de visualizações de página neste mês.',
    'log_note_captcha_this_month' => 'Estatísticas de CAPTCHA deste mês.',
    'log_note_captcha_today' => 'Estatísticas de CAPTCHA de hoje.',
    'log_note_pageview_today' => 'Total de visualizações de página de hoje.',
    'log_note_pageview_yesterday' => 'Total de visualizações de página de ontem.',
    'log_note_captcha_yesterday' => 'Estatísticas de CAPTCHA de ontem.',
    
    'log_label_last_month' => 'Mês passado',
    'log_label_this_month' => 'Este mês',
    'log_label_last_7_days' => 'Últimos 7 dias',
    'log_label_yesterday' => 'Ontem',
    'log_label_today' => 'Hoje',
    'log_msg_no_logger' => 'Desculpe, você precisa implementar o ActionLogger para usar esta funcionalidade.',
    'log_label_in_queue' => 'Na fila',
    'log_label_in_blacklist' => 'Na lista negra',
    'log_label_captcha' => 'CAPTCHA',
    'log_label_pageviews' => 'Visualizações de Página',
    'log_label_session' => 'Sessões',
    'log_label_solved' => 'resolvido',
    'log_label_failed' => 'falhou',
    'log_label_displays' => 'exibições',
    'log_label_timezone' => 'Fuso horário',
    'log_label_cache_time' => 'Horário de geração do relatório',


    // Overview
    'overview_heading_data_circle' => 'Círculo de Dados',
    'overview_label_mysql' => 'MySQL',
    'overview_text_rows' => 'linhas',
    'overview_note_sql_db' => 'Banco de dados SQL.',
    'overview_note_memory_db' => 'Banco de dados em memória.',
    'overview_label_redis' => 'Redis',
    'overview_btn_close' => 'Fechar',
    'overview_btn_save' => 'SALVAR',
    'overview_note_image_captcha' => 'Um simples Captcha com texto na imagem.',
    'overview_label_image_captcha' => 'Captcha de Imagem',
    'overview_note_recaptcha' => 'Fornecido pelo Google.',
    'overview_label_recaptcha' => 'reCAPTCHA',
    'overview_heading_captcha' => 'Módulos de Captcha',
    'overview_note_action_logger' => 'Registra o comportamento de cada visitante.',
    'overview_label_action_logger' => 'Registrador de Ações',
    'overview_heading_logger' => 'Logger',
    'overview_text_since' => 'desde',
    'overview_text_days' => 'dias',
    'overview_text_size' => 'tamanho',
    'overview_note_useragent' => 'Analisa as informações do user-agent dos visitantes.',
    'overview_label_useragent' => 'User Agent',
    'overview_note_rdns' => 'Identifica o hostname resolvido (RDNS) do IP do visitante.',
    'overview_label_rdns' => 'RDNS',
    'overview_note_header' => 'Analisa as informações de cabeçalho dos visitantes.',
    'overview_label_header' => 'Cabeçalho',
    'overview_note_trustedbot' => 'Permite que mecanismos de busca populares rastreiem seu site.',
    'overview_label_trustedbot' => 'Bot Confiável',
    'overview_note_ip' => 'Gerenciamento avançado de endereços IP.',
    'overview_label_ip' => 'IP',
    'overview_heading_components' => 'Componentes',
    'overview_note_referer' => 'Verifica as informações do referenciador HTTP.',
    'overview_label_referer' => 'Referenciador',
    'overview_note_frequency' => 'Verifica com que frequência o visitante visualiza páginas.',
    'overview_label_frequency' => 'Frequência',
    'overview_note_session' => 'Detecta se múltiplas sessões foram criadas pelo mesmo visitante.',
    'overview_label_session' => 'Sessão',
    'overview_note_cookie' => 'Verifica se os visitantes podem criar cookies via JavaScript.',
    'overview_label_cookie' => 'Cookie',
    'overview_heading_filters' => 'Filtros',
    'overview_label_sqlite' => 'SQLite',
    'overview_note_file_system' => 'Sistema de arquivos.',
    'overview_label_file' => 'Arquivo',
    'overview_reset_data_circle' => 'Redefinir Círculo de Dados',
    'overview_reset_action_logs' => 'Redefinir Logs de Ações',
    'overview_thread_rows' => 'Linhas',
    'overview_thread_table' => 'Tabela',
    'overview_text_reset_data_circle_1' => 'Deseja redefinir o círculo de dados atual?',
    'overview_text_reset_data_circle_2' => 'Executar esta ação removerá todos os dados do círculo de dados atual e reconstruirá as tabelas. Você será desconectado do painel de controle.',
    'overview_text_reset_action_logs' => 'Deseja remover todos os logs de ações?',
    'overview_heading_messenger' => 'Módulos de Notificação',
    'overview_label_telegram' => 'Telegram',
    'overview_note_telegram' => 'Envia notificações para seu canal no Telegram.',
    'overview_label_linenotify' => 'Line Notify',
    'overview_note_linenotify' => 'Envia notificações para seu grupo no Line.',
    'overview_label_sendgrid' => 'SendGrid',
    'overview_note_sendgrid' => 'Envia notificações para seu e-mail através da API do SendGrid.',
    'overview_label_slack' => 'Slack',
    'overview_note_slack' => 'Envia notificações para seu canal no Slack através da API do Slack.',
    'overview_label_slackwebhook' => 'Webhook do Slack',
    'overview_note_slackwebhook' => 'Envia notificações para seu canal no Slack através de Webhook.',
    'overview_label_mailgun' => 'MailGun',
    'overview_note_mailgun' => 'Envia notificações para seu e-mail através da API do MailGun.',
    'overview_label_smtp' => 'SMTP',
    'overview_note_smtp' => 'Envia notificações para seu e-mail através de um servidor SMTP.',
    'overview_label_rocketchat' => 'RocketChat',
    'overview_note_rocketchat' => 'Envia notificações para seu canal no RocketChat.',
    'overview_label_mail' => 'Mail',
    'overview_note_mail' => 'Envia notificações para seu e-mail usando a função de e-mail nativa do PHP.',


    // IP log table.
    'table_heading_ip_log' => 'Tabela de Log de IP',
    'table_description_ip_log_1' => 'É aqui que o Shieldon registra comportamentos estranhos dos usuários.',
    'table_description_ip_log_3' => 'A tabela de log de IP será totalmente limpa quando um novo ciclo começar.',
    'table_label_resolved_hostname' => 'Hostname resolvido',
    'table_label_last_visit' => 'Última visita',
    'table_label_flags' => 'Flags',
    
    // Tabela de regras.
    'table_heading_rule' => 'Tabela de Regras',
    'table_description_rule_1' => 'O Shieldon permite ou nega temporariamente o acesso dos usuários nesta tabela.',
    'table_description_rule_3' => 'A tabela de regras será redefinida quando um novo ciclo começar.',
    'table_label_deny_ip_temporarily' => 'Bloquear este IP temporariamente',
    'table_label_deny_ip_permanently' => 'Bloquear este IP permanentemente',
    'table_ip_placeholder' => 'Por favor, insira um endereço IP...',
    'table_label_type' => 'Tipo',
    'table_label_reason' => 'Motivo',
    'table_label_time' => 'Hora',
    'table_label_remove' => 'Remover',
    
    // Tabela de sessões.
    'table_heading_session' => 'Tabela de Sessões',
    'table_label_remain_seconds' => 'Segundos Restantes',
    'table_label_priority' => 'Prioridade',
    'table_label_status' => 'Status',
    'table_label_session_id' => 'ID da Sessão',
    'table_text_allowable' => 'Permitido',
    'table_text_expired' => 'Expirado',
    'table_text_waiting' => 'Aguardando',
    'table_description_session_1' => 'Logs em tempo real do <strong>Controle de Sessões Online</strong>.',
    'table_description_session_2' => 'Atenção: só funciona se estiver ativado.',
    'table_heading_limit' => 'Limite',
    'table_note_limit' => 'Limite de sessões online.',
    'table_heading_period' => 'Período',
    'table_note_period' => 'Período de atividade (em minutos)',
    'table_heading_online' => 'Online',
    'table_note_online' => 'Contagem de usuários online.',
    
    // Proteção XSS.
    'xss_heading' => 'Proteção XSS',
    'xss_description' => 'Previne ataques de Cross-Site Scripting (XSS).',
    'xss_label_variable' => 'Variável',
    'xss_text_eradicate_injection' => 'Erradicar possíveis strings de injeção para variável única.',
    'xss_label_single_variable' => 'Variável única',
    'xss_label_variable_name' => 'Nome da Variável',
    'xss_text_update_above_settings' => 'Atualizar configurações acima.',
    'xss_text_filter_cookie_variables' => 'Filtrar todas as variáveis do método COOKIE.',
    'xss_text_filter_get_variables' => 'Filtrar todas as variáveis do método GET.',
    'xss_text_filter_post_variables' => 'Filtrar todas as variáveis do método POST.',
    
    // Abas
    'tab_heading_adminlogin' => 'Login do Admin',
    'tab_heading_dialogui' => 'Interface de Diálogo',
    'tab_heading_captchas' => 'CAPTCHAs',
    'tab_heading_filters' => 'Filtros',
    'tab_heading_components' => 'Componentes',
    'tab_heading_daemon' => 'Daemon',


    // Setting - admin login.
    'setting_heading_adminlogin' => 'Login do Admin',
    'setting_label_last_modified' => 'Última Modificação',
    'setting_label_password' => 'Senha',
    'setting_label_user' => 'Usuário',
    
    // Configuração - captcha.
    'setting_heading_recaptcha' => 'reCAPTCHA',
    'setting_label_recaptcha_key' => 'Chave do Site',
    'setting_note_recaptcha_key' => 'Insira a chave do site do Google reCAPTCHA para seu site.',
    'setting_label_recaptcha_secret' => 'Chave Secreta',
    'setting_note_recaptcha_secret' => 'Insira a chave secreta do Google reCAPTCHA para seu site.',
    'setting_label_recaptcha_version' => 'Versão',
    'setting_note_recaptcha_version' => 'Use a chave correspondente à versão que você escolher, caso contrário não funcionará.',
    'setting_label_recaptcha_lang' => 'Código de Idioma',
    'setting_note_recaptcha_lang' => 'Código ISO 639 - ISO 3166. Por exemplo, zh-TW representa Chinês Tradicional de Taiwan.',
    'setting_note_image_captcha_1' => 'Sequência alfanumérica com letras minúsculas e maiúsculas.',
    'setting_note_image_captcha_2' => 'Sequência com apenas letras minúsculas e maiúsculas.',
    'setting_note_image_captcha_3' => 'Apenas números.',
    'setting_note_image_captcha_length' => 'Quantos caracteres você deseja exibir no CAPTCHA.',
    'setting_label_length' => 'Comprimento',
    'setting_heading_image_captcha' => 'Imagem',
    
    // Configuração - componente.
    'setting_heading_component_ip' => 'IP',
    'setting_note_component_ip' => 'Ative o Gerenciador de IPs ativando esta opção.',
    'setting_heading_component_tb' => 'Bots Confiáveis',
    'setting_note_component_tb_1' => 'Permitir que mecanismos de busca populares rastreiem seu site.',
    'setting_note_component_tb_2' => 'Atenção: Desativar esta opção afetará seu SEO, pois os bots passarão pelo processo de verificação.',
    'setting_label_strict_mode' => 'Modo Rigoroso',
    'setting_note_component_tb_3' => 'O nome do host resolvido (PTR) e o endereço IP devem coincidir.',
    'setting_heading_component_header' => 'Cabeçalho',
    'setting_note_component_header_1' => 'Analisar as informações do cabeçalho dos visitantes.',
    'setting_note_component_header_2' => 'Negar todos os visitantes sem informações comuns no cabeçalho.',
    'setting_heading_component_useragent' => 'User Agent',
    'setting_note_component_useragent_1' => 'Analisar as informações do user-agent dos visitantes.',
    'setting_note_component_useragent_2' => 'Visitantes com user-agent vazio serão bloqueados.',
    'setting_heading_component_rdns' => 'DNS Reverso',
    'setting_note_component_rdns_1' => 'Em geral, um IP de um provedor de Internet (ISP) costuma ter o RDNS configurado. Esta opção só funciona quando o modo rigoroso está ativado.',
    'setting_note_component_rdns_2' => '
                O modo rigoroso bloqueia visitantes pelas seguintes condições.<br />
                - Endereço IP sem registro PTR.<br />
                - Valor retornado ao pingar o PTR e o IP não corresponde.<br />
                - PTR não é um FQDN válido.<br />
                Esta opção bloqueará quase todos os servidores Proxy e VPN da internet, e alguns ISPs podem não fornecer PTR para seus IPs. Use com cautela.
            ',
    

    // Setting - daemon
    'setting_heading_enable' => 'Ativar',
    'setting_label_data_driver' => 'Driver de Dados',
    'setting_note_data_driver' => 'Comece a proteger seu site implementando o Shieldon. O Firewall Shieldon só funciona quando esta opção está ativada.',
    'setting_label_driver_file' => 'Sistema de Arquivos',
    'setting_label_driver_mysql' => 'MySQL',
    'setting_label_driver_redis' => 'Redis',
    'setting_label_driver_sqlite' => 'SQLite',
    'setting_label_mysql_host' => 'Host',
    'setting_label_mysql_dbname' => 'Nome do Banco',
    'setting_label_mysql_user' => 'Usuário',
    'setting_label_mysql_password' => 'Senha',
    'setting_label_mysql_charset' => 'Charset',
    'setting_label_redis_host' => 'Host',
    'setting_label_redis_port' => 'Porta',
    'setting_label_redis_auth' => 'Autenticação',
    'setting_note_redis_auth' => 'Necessário apenas se for exigida uma senha.',
    'setting_note_driver_not_recommended' => 'Não recomendado para sites com alto tráfego.',
    'setting_label_directory' => 'Diretório',
    'setting_note_directory' => 'Caminho absoluto do diretório onde os dados serão armazenados.',
    'setting_label_reset_data_cycle' => 'Redefinir Ciclo de Dados',
    'setting_note_reset_data_cycle' => 'Limpa todos os registros automaticamente todos os dias à 0h. Ativar esta opção melhora o desempenho.',
    'setting_label_ip_source' => 'Fonte de IP',
    'setting_note_ip_source' => 'Seu site está por trás de um serviço CDN? Se estiver, configure corretamente esta opção; caso contrário, todos os IPs dos servidores CDN poderão ser banidos.',
    'setting_label_session_limit' => 'Limite de Sessões',
    'setting_note_session_limit_1' => 'Quando o número de usuários online atingir o limite, os usuários fora da fila terão que esperar!',
    'setting_note_session_limit_2' => 'A imagem a seguir é um exemplo.',
    'setting_label_online_limit' => 'Limite de Usuários Online',
    'setting_note_online_limit' => 'Número máximo de usuários online.',
    'setting_label_alive_period' => 'Período de Atividade',
    'setting_note_alive_period' => 'Unidade: minuto.',
    'setting_label_action_logs' => 'Logs de Ações',
    'setting_label_action_logger' => 'Registrador de Ações',
    'setting_heading_dailogui' => 'Interface do Diálogo',
    'setting_label_language' => 'Idioma',
    'setting_label_background_image' => 'Imagem de Fundo',
    'setting_note_background_image' => 'Informe a URL completa ou o caminho relativo da imagem.',
    'setting_label_background_color' => 'Cor de Fundo',
    'setting_note_background_color' => 'Você pode especificar uma cor de fundo caso não deseje usar uma imagem.',
    'setting_label_dialog_header' => 'Cabeçalho do Diálogo',
    'setting_text_for_example' => 'Por exemplo',
    'setting_label_font_color' => 'Cor da Fonte',
    'setting_label_shadow_opacity' => 'Opacidade da Sombra',
    'setting_note_shadow_opacity' => 'Intervalo de 0 a 1, por exemplo, 0.2 significa 20% de opacidade.',
    'setting_heading_filter_frequency' => 'Frequência',
    'setting_note_filter_frequency_1' => 'Não se preocupe com visitantes humanos — se forem bloqueados ao atingir o limite, poderão continuar acessando seu site resolvendo o CAPTCHA.',
    'setting_note_filter_frequency_2' => 'A imagem a seguir é um exemplo.',
    'setting_label_secondly_limit' => 'Limite por Segundo',
    'setting_label_minutely_limit' => 'Limite por Minuto',
    'setting_label_hourly_limit' => 'Limite por Hora',
    'setting_label_daily_limit' => 'Limite por Dia',
    'setting_note_secondly_limit' => 'Visualizações de página por visitante por segundo.',
    'setting_note_minutely_limit' => 'Visualizações de página por visitante por minuto.',
    'setting_note_hourly_limit' => 'Visualizações de página por visitante por hora.',
    'setting_note_daily_limit' => 'Visualizações de página por visitante por dia.',
    'setting_label_filter_cookie' => 'Cookie',
    'setting_label_filter_session' => 'Sessão',
    'setting_note_filter_session' => 'Detecta se múltiplas sessões foram criadas pelo mesmo visitante.',
    'setting_label_filter_referer' => 'Referenciador',
    'setting_note_filter_referer' => 'Verifica as informações do referenciador HTTP.',
    'setting_label_quota' => 'Cota',
    'setting_note_quota' => 'Um visitante que atingir esse limite será temporariamente bloqueado.',
    'setting_label_buffered_time' => 'Tempo de Espera',
    'setting_note_buffered_time' => 'Inicia o uso deste filtro após n segundos da primeira visita ao seu site.',

    'setting_label_cookie_name' => 'Nome do Cookie',
    'setting_note_cookie_name' => 'Apenas caracteres em inglês.',
    'setting_label_cookie_value' => 'Valor do Cookie',
    'setting_label_cookie_domain' => 'Domínio do Cookie',
    'setting_text_leave_blank' => 'Deixe em branco para aplicar o padrão.',
    'setting_heading_deny_attempts' => 'Negar Tentativas',
    'setting_desc_deny_attempts' => 'Diga adeus aos visitantes mal-intencionados.',
    'setting_label_system_firewall' => 'Firewall do Sistema',
    'setting_note_install_iptables' => 'Certifique-se de que você já instalou <strong>iptables</strong> e <strong>ip6tables</strong> no seu servidor, e utilizou corretamente o <strong>iptables_bridge.sh</strong> no <strong>crontab</strong>.',
    'setting_label_watching_folder' => 'Pasta Monitorada',
    'setting_label_cronjob' => 'Tarefa Cron',
    'setting_note_cronjob' => 'Insira este código no arquivo crontab do seu servidor.',
    'setting_note_iptables' => '<strong>iptables_bridge.sh</strong> vai monitorar mudanças nesta pasta para aplicar comandos ao iptables.',
    'setting_note_iptables_bridge' => 'Mova o <strong>iptables_bridge.sh</strong> para um local seguro acessível apenas por você, alterando o caminho por razões de segurança.',
    'setting_label_deny_attempt_buffer' => 'Buffer',
    'setting_desc_deny_attempt_buffer' => 'Quantas falhas consecutivas irão acionar este evento.',
    'setting_label_record_attempt_detection_period' => 'Período de Detecção',
    'setting_desc_record_attempt_detection_period' => 'Verifica a diferença de tempo entre agora e a última tentativa falha. Tentativas dentro desse intervalo serão registradas. Um valor maior torna o filtro mais rigoroso. (unidade: segundos)',
    'setting_label_record_attempt_reset' => 'Redefinir',
    'setting_desc_record_attempt_reset' => 'Zerar o contador após n segundos.',
    'setting_button_choose_file' => 'Escolher arquivo',
    'setting_note_import' => 'Por favor, selecione o arquivo .json exportado anteriormente.',
    'setting_button_export' => 'Exportar',
    'setting_button_import' => 'Importar',
    'setting_label_unique_ip_only' => 'IP Único',
    'setting_note_unique_ip_only' => 'Permitir apenas uma sessão por endereço IP.',
    'setting_note_unique_ip_only_2' => 'Usuários com várias sessões serão desconectados.',
    
    // Adicionado em 19/08/2020
    'setting_heading_dialog_information' => 'Divulgação de Informações',
    'setting_label_dialog_user_inforamtion' => 'Informações do Usuário',
    'setting_note_dialog_user_inforamtion' => 'Exibir endereço IP, RDNS e user-agent.',
    
    'setting_label_dialog_http_status' => 'Código de Status HTTP',
    'setting_note_dialog_http_status' => 'Exibir o código de status HTTP aos usuários.',
    
    'setting_label_dialog_reason_code' => 'Código do Motivo',
    'setting_note_dialog_reason_code' => 'Exibir o código que causou o bloqueio do usuário.',
    
    'setting_label_dialog_reason_text' => 'Texto do Motivo',
    'setting_note_dialog_reason_text' => 'Exibir o texto que explica o motivo do bloqueio do usuário.',
    'setting_note_dialog_reason_notice' => 'Não é recomendado exibir essas informações, pois pessoas mal-intencionadas podem descobrir formas de burlar a proteção.',
    
    'setting_label_dialog_user_amount' => 'Contagem de usuários online',
    'setting_note_dialog_user_amount' => 'Exibir o número total de usuários online ao mostrar o aviso de limite de sessões.',


    // Messenger
    'messenger_heading_events' => 'Eventos',
    'messenger_desc_events' => 'Quais eventos você gostaria de receber notificações enviadas pelos módulos do Messenger.',
    'messenger_label_event_1' => 'Banir usuário no ciclo de dados atual.',
    'messenger_desc_event_1' => 'Este evento é geralmente acionado quando um usuário falha muitos CAPTCHAs seguidos.',
    'messenger_label_event_2' => 'Banir permanentemente usuário no firewall do sistema',
    'messenger_desc_event_2' => 'Este evento é geralmente acionado quando um usuário já está banido no ciclo de dados atual, mas continua acessando as páginas de aviso muitas vezes seguidas — podemos concluir que se trata de bots maliciosos.',
    'messenger_desc_event_3' => 'Esta opção só terá efeito se você tiver configurado corretamente o firewall em nível de sistema.',
    'messenger_heading_telegram' => 'Telegram',
    'messenger_label_api_key' => 'Chave da API',
    'messenger_label_channel' => 'Canal',
    'messenger_heading_linenotify' => 'Line Notify',
    'messenger_label_access_token' => 'Token de Acesso',
    'messenger_heading_sendgrid' => 'SendGrid',
    'messenger_label_sender' => 'Remetente',
    'messenger_label_recipients' => 'Destinatários',
    'messenger_label_host' => 'Host',
    'messenger_label_port' => 'Porta',
    'messenger_label_user' => 'Usuário',
    'messenger_label_pass' => 'Senha',
    'messenger_label_type' => 'Tipo',
    'messenger_heading_mailgun' => 'MailGun',
    'messenger_heading_smtp' => 'SMTP',
    'messenger_heading_php_mail' => 'Mail Nativo do PHP',
    'messenger_label_webhook_url' => 'URL do Webhook',
    'messenger_label_bot_token' => 'Token do Bot',
    'messenger_heading_slack' => 'Slack',
    'messenger_heading_slack_webhook' => 'Webhook do Slack',
    'messenger_heading_rocket_chat' => 'Rocket Chat',
    'messenger_label_server_url' => 'URL do Servidor',
    
    'tab_heading_events' => 'Eventos',
    'tab_heading_modules' => 'Módulos',
    'tab_heading_iptables_status' => 'Status',
    
        
    'error_ip6tables_directory_not_writable' => 'A pasta monitorada pelo iptables requer permissão de escrita no diretório de armazenamento.',
    
    'iptable_heading' => 'Gerenciador do iptables',
    'iptable_description_1' => 'Esta é a Interface Web do <strong>iptables</strong>, use esta função com cautela.',
    'iptable_description_2' => 'Você pode gerenciar apenas requisições de entrada aqui.',
    'iptable_description_3' => 'Após reiniciar o servidor, as regras aqui desaparecerão. Use o <strong>iptables-save</strong> por conta própria para manter as regras salvas.',
    'ip6table_description_1' => 'Esta é a Interface Web do <strong>ip6tables</strong>, use esta função com cautela.',
    'ip6table_description_2' => 'Você pode gerenciar apenas requisições de entrada aqui.',
    'ip6table_description_3' => 'Após reiniciar o servidor, as regras aqui desaparecerão. Use o <strong>ip6tables-save</strong> por conta própria para manter as regras salvas.',
    'iptables_label_subnet' => 'Sub-rede',
    'iptables_label_port' => 'Porta',
    'iptables_label_port_custom' => 'Personalizada',
    'iptables_label_protocol' => 'Protocolo',
    'iptables_label_protocol_all' => 'Todos',
    'iptables_label_protocol_tcp' => 'TCP',
    'iptables_label_protocol_udp' => 'UDP',
    'iptables_label_action_allow' => 'permitir',
    'iptables_label_action_deny' => 'bloquear',
    'iptable_status_description' => 'O texto a seguir é o resultado do comando <code>iptables -L</code>.',
    'ip6table_status_description' => 'O texto a seguir é o resultado do comando <code>ip6tables -L</code>.',
    
    'reset_data_circle' => 'Tabelas de dados do círculo foram redefinidas.',
    'reset_action_logs' => 'Registros de ações foram removidos.',
    
    'operation_note_useragent' => 'Bloquear requisições sem informações de user-agent.',
    'operation_note_rdns' => 'Bloquear requisições sem registro RDNS.',
    'operation_note_header' => 'Bloquear requisições sem cabeçalhos comuns.',
    'operation_note_trustedbot' => 'Bloquear requisições identificadas como bots falsos de mecanismos de busca.',
    'operation_note_ip' => 'Bloquear requisições usando as regras definidas no Gerenciador de IPs.',
    
    'login_heading_login' => 'Login no Painel do Firewall.',
    'login_btn_login' => 'Entrar',
    'login_message_invalid_captcha' => 'Captcha inválido',
    'login_message_invalid_user_or_pass' => 'Usuário ou senha inválidos.',
    
    'test_msg_title' => 'Mensagem de Teste do Host: ',
    'test_msg_body' => 'O módulo Messenger {0} foi testado e confirmado com sucesso.',

];
